baseURL: "https://jasstkn.github.io/"
languageCode: "en-us"
title: "DevOops notes"
theme: "cupper-hugo-theme"

permalinks:
  post: /:filename/

menu:
  nav:
  - name: Home
    url: /
    weight: 1
  - name: Blog
    url: /posts/
    weight: 2
  # - name: About
  #   url: /about/
  #   weight: 3

params:
  description: Maria is behind the wheel today
  homeMetaContent: Maria is behind the wheel today.
  # TODO: add links
  # footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Github](https://github.com/).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
